### ISSUE TITLE
Could not find module ‘Distribution.Simple’

### ISSUE THREAD

**Issue by talios** [ghcformacosx/ghc-dot-app#1]
I understand `ghx-dot-app` only includes the cabal binary, and not the library, which this problem seems to be related to.

```
cabal install aeson
Resolving dependencies...
Downloading aeson-0.7.0.6...
Configuring aeson-0.7.0.6...
Failed to install aeson-0.7.0.6
Last 10 lines of the build log ( /Users/amrk/.cabal/logs/aeson-0.7.0.6.log ):
cabal: Error: some packages failed to install:
aeson-0.7.0.6 failed during the configure step. The exception was:
user error (
/var/folders/2h/76nn14b502q410szcd74lv200000gn/T/aeson-0.7.0.6-8781/aeson-0.7.0.6/dist/setup/setup.hs:1:8:
Could not find module ‘Distribution.Simple’
There are files missing in the ‘Cabal-1.20.0.0’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
)
```

Running `ghc-pkg check` yields an insanely large list of broken packages, running `cabal install cabal --reinstall` seems to build the library and lets me move on but seems to yield many more issues.

This all seemed to work fine on another machine, but not on this machine ( which used to have a homebrew haskell platform install ) - but given this is supposed to be self contained, I didn't think that should have mattered.

**Comment by briancavalier** [comment]
I just started using ghc and cabal from homebrew, and I ran into the same issue.  Thankfully, google led me here, and removing my `~/.ghc/` dir got me back to a working state.  Thanks!

**Comment by tgerder** [comment]
same on windows 7 at:
%HOMEPATH%\AppData\Roaming\ghc
e.g. delete and run
cabal update && cabal list --simple-output --installed | awk '{print $1}' | uniq | xargs -I {} cabal install {} --reinstall

**Comment by mrkgnao** [comment]
I'm on Linux, but this fix worked for me too. Thanks.
