### ISSUE TITLE
Instructions use GHC.app, but the file unzips to ghc-7.8.3

### ISSUE THREAD

**Issue by MaxGabriel** [ghcformacosx/ghc-dot-app#16]
The current instructions say to use a path like `/Applications/GHC.app`, but the named of the unzipped download is `ghc-7.8.3.app`. I was able to figure this out pretty easily but it would have been easier if the file was named `GHC.app` or the instructions used `ghc-7.8.3` in them.

```
# Add GHC 7.8.3 to the PATH, via http://ghcformacosx.github.io/
export GHC_DOT_APP="/Applications/GHC.app"
if [ -d "$GHC_DOT_APP" ]; then
    export PATH="${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
fi
```

**Comment by etrepum** [comment]
The latest release (v7.8.4-r1) should be much more robust, all of the shell stuff has been refactored to support bash and zsh and now it looks for particular prefixes in the output.
