### ISSUE TITLE
ghc-7.8.4

### ISSUE THREAD

**Issue by cdornan** [ghcformacosx/ghc-dot-app#20]
Is a 7.8.4 release planned?

I see that you are considering adding packages -- could I suggest that you do not do this! Or at least retain the option of a minimal installation. At least for me, the value of this distribution (for now) is that it nicely packages a minimal ghc.

Thanks for the very nice package!

**Comment by etrepum** [comment]
I'll do a 7.8.4 release when official Mac binaries are made available.

**Comment by ijuma** [comment]
This issue should probably be closed as 7.8.4 was released a while back.
