### ISSUE TITLE
It burninated my .bash_profile

### ISSUE THREAD

**Issue by Jks15063** [ghcformacosx/ghc-dot-app#21]
Many if not all of my settings in .bash_profile were lost when I ran this.

**Comment by etrepum** [comment]
Which dotfiles do you have in your home directory? What is the contents of the file after running the app?

It does make a .ghc.orig backup file before appending.

My suspicion is a that your file is unchanged but it wrote to another file that has higher priority.

**Comment by etrepum** [comment]
Please re-open when you have any details to provide, there's nothing actionable in this report.

Here's the relevant code in the helper application. You can see that it will either create a new file, or it will make a backup copy of your profile and append: https://github.com/ghcformacosx/ghc-dot-app/blob/master/GHC/GHC/GHCAppDelegate.m#L275-L312
