### ISSUE TITLE
Cannot install ghc plattform if using zsh as shell

### ISSUE THREAD

**Issue by farolfo** [ghcformacosx/ghc-dot-app#22]
Hey there, I'm finding this issue while installing ghc. Any idea how to fix this? I've alraedy change the SHELL env variable to /bin/bash and no changes.
![screen shot 2015-02-14 at 9 14 54 pm](https://cloud.githubusercontent.com/assets/1851436/6201535/9cc02388-b48e-11e4-9927-aac2832452e0.png)

**Comment by farolfo** [comment]
chsh -s /bin/bash this isn't working either BTW

**Comment by etrepum** [comment]
Yes, you'll have to modify your shell config by hand. You may be able to copy and paste the code from the textbox as-is.

**Comment by etrepum** [comment]
The only thing that application does is diagnose and help resolve PATH issues (for bash). It looks like you've already set your PATH appropriately.

**Comment by farolfo** [comment]
I see the path is well configured, but no cabal installation has happened

**Comment by etrepum** [comment]
The `.cabal` folder will be created when you run `cabal update` for the first time.

**Comment by siemiatj** [comment]
So do I need to install cabal manually ? I don't have `HOME/.cabal` folder

**Comment by etrepum** [comment]
See the previous commen
