### ISSUE TITLE
Support zsh

### ISSUE THREAD

**Issue by etrepum** [ghcformacosx/ghc-dot-app#23]

**Comment by Duozhasht** [comment]
Any instructions ?

**Comment by etrepum** [comment]
Copy and paste the given text into the appropriate startup file for zsh.

**Comment by Duozhasht** [comment]
yy it worked, i've already tried that, but i thought the .app file was some kind of installer that only would go forward if didn't show no warnings. But i just added path (with some modifications) and ghc works on terminal already ;)
ty !

**Comment by cbowns** [comment]
The `zsh` support I encountered today was quite odd. I'll write up issues around it.

**Comment by etrepum** [comment]
No need for separate issues. There is no zsh support, this is the issue tracking that.
