### ISSUE TITLE
Versions of Mac OS X supported?

### ISSUE THREAD

**Issue by FranklinChen** [ghcformacosx/ghc-dot-app#24]
https://www.haskell.org/downloads/osx says "This download is provided by GHC for OS X for 64-bit Mac OS X 10.9 and later." I'm running 10.7.5 on a 2008 MacBook and GHC 7.8.3 works there. Is it the end of the line then for this old Mac?

**Comment by etrepum** [comment]
The helper app won't work, because it was built with APIs that did not exist back then, but the GHC inside will likely work if you put it on your PATH.

You can also just download the bindist and configure/install it. http://www.ozonehouse.com/mark/platform/ghc-7.8.4-x86_64-apple-darwin.tar.bz2

You may be able to use Homebrew.

**Comment by FranklinChen** [comment]
For the record, the Homebrew build resulted in a non-functioning compiler, while http://www.ozonehouse.com/mark/platform/ghc-7.8.4-x86_64-apple-darwin.tar.bz2 won't even let me run `configure` without a mysterious error, so I'm just going to assume old Macs are no longer supported and not invest any more time into the matter.

**Comment by etrepum** [comment]
Certainly not actively supported. Unfortunately it looks like your model of Mac is at the cut-off year for being able to upgrade, anything newer than that would be able to run the latest OS (I'm assuming it's not a late 2008 MacBook). https://www.apple.com/osx/how-to-upgrade/

**Comment by FranklinChen** [comment]
Yes, I missed the cutoff, with an early 2008 black polycarbonate MacBook.

I have a recent MacBook Pro that feels orders of magnitude faster and works fine. I just get a little sad when a perfectly functioning old computer is no longer supported for many things. Heck, I have a 2002 12" Mac PowerBook (PowerPC G4) that still functions too, and a 1993 Mac PowerBook 145B (68030) that still "works", on which I first learned Haskell through Gofer, Yale Haskell, and later Hugs and GHC!

**Comment by etrepum** [comment]
Linux is usually a reasonable option for older Mac hardware

**Comment by FranklinChen** [comment]
Quite true. However, my 2008 MacBook currently has an important function as an iTunes server :-). In principle I could move off proprietary Apple software, of course. I have done that before (1995-2002 I abandoned Apple for Linux).
