### ISSUE TITLE
Problem installing gloss

### ISSUE THREAD

**Issue by nateuni** [ghcformacosx/ghc-dot-app#25]
I have tried everything to get this to work (before finding your package). but I am still getting this issue:
```
uilding gloss-raster-1.9.2.1...
Preprocessing library gloss-raster-1.9.2.1...
[1 of 2] Compiling Graphics.Gloss.Raster.Array ( Graphics/Gloss/Raster/Array.hs, dist/build/Graphics/Gloss/Raster/Array.o )

<no location info>:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM
ghc: could not execute: opt
```

**Comment by etrepum** [comment]
How exactly are you getting to this point?

**Comment by nateuni** [comment]
cabal install gloss-examples

I am have installed llvm34 via brew and I have symlinked llc and opt to it. And I am in the process of retrying the install.

**Comment by nateuni** [comment]
Ok that worked!
