### ISSUE TITLE
Use potionfactory/LetsMove to move the app bundle to /Applications

### ISSUE THREAD

**Issue by cbowns** [ghcformacosx/ghc-dot-app#26]
https://github.com/potionfactory/LetsMove is a great little project most Mac apps use to detect when they're launched outside of `/Applications` to offer to copy/move themselves there (and automatically quit-and-relaunch).

**Comment by etrepum** [comment]
What problem(s) did you encounter that this would fix?

**Comment by etrepum** [comment]
Going to close this for now. It's not quite clear what problem this would solve. Are you asking for "Copy to /Applications" functionality as a button or dialog?

**Comment by cbowns** [comment]
When I launched GHC off the downloaded DMG, it knew it wasn't in /Applications, but needed me to copy it there. LetsMove provides a way to say, "cool, copy yourself there and relaunch". It automates what the app currently asks the user to do.

**Comment by etrepum** [comment]
The app asks you to put it anywhere but downloads. That project expects Applications folder. I'll take that info consideration as a feature request.
