### ISSUE TITLE
GHC 7.10.1

### ISSUE THREAD

**Issue by ijuma** [ghcformacosx/ghc-dot-app#27]
GHC 7.10.1 is out[1] and it would be great to have a release with that. It looks like Mac binaries are not yet available though[2].

[1] https://mail.haskell.org/pipermail/haskell/2015-March/024499.html
[2] https://downloads.haskell.org/~ghc/7.10.1/

**Comment by jhenahan** [comment]
Mac binaries [should be going up this weekend](https://www.reddit.com/r/haskell/comments/30gyie/announce_ghc_version_7101/cpsgxt1?context=1).

**Comment by etrepum** [comment]
I'll allocate some time on Sunday to do a release provided that binaries are available. If not, then early next week.

**Comment by lvicentesanchez** [comment]
+1

**Comment by etrepum** [comment]
GHC is available, but Cabal's available binaries are lagging behind. Only 1.22.0.0 is available. I think this may be sufficient for 7.10.1.
