### ISSUE TITLE
cabal: /Users/<username>/Library: does not exist

### ISSUE THREAD

**Issue by rocurley** [ghcformacosx/ghc-dot-app#32]
After following the instructions in the app, running `cabal` works, yielding:
```
cabal: no command given (try --help)
```
However running `cabal update` yields
```
Downloading the latest package list from hackage.haskell.org
cabal: /Users/rcurley/Library: does not exist
```

**Comment by etrepum** [comment]
Have you installed Haskell Platform in the past? There may be an issue with your `~/.cabal/config`

**Comment by rocurley** [comment]
Yep, that was it. Removing my `~/.cabal` file fixed it.
