### ISSUE TITLE
documentation links are wrong

### ISSUE THREAD

**Issue by alexeymuranov** [ghcformacosx/ghc-dot-app#33]
Clicking "Open GHC Docs" opens a local page. Clicking then, for example, "Libraries", opens another local page.  Clicking then almost anything does not open anything, because links are bad.

**Comment by etrepum** [comment]
I can reproduce, something must've changed in GHC 7.10.

**Comment by elfenlaid** [comment]
yep, I'm also can't download *7.10.1-r0* with `Error code: ERR_CONNECTION_REFUSED`

**Comment by etrepum** [comment]
Your issue with downloading is unrelated to this. Downloads are hosted by GitHub.

**Comment by elfenlaid** [comment]
oh, I see, sorry for disturbing

**Comment by adityav** [comment]
I am facing the same problem

**Comment by etrepum** [comment]
The root cause for this is in GHC build process somewhere, hopefully will be fixed in 7.10.2.

**Comment by etrepum** [comment]
GHC 7.10.2 doesn't seem to have this problem
