### ISSUE TITLE
Cabal version in 7.8.4 is wrong

### ISSUE THREAD

**Issue by dhobbs** [ghcformacosx/ghc-dot-app#34]
The version of cabal bundled with 7.8.4 appears to be too new. According to the cabal website it should be Cabal 1.18.1.5. The bundled version breaks ghc-mod.

**Comment by etrepum** [comment]
As a workaround, you can install the version of `cabal-install` that you want yourself. Or compile `ghc-mod` master from git (which works, even with GHC 7.10.1).

**Comment by etrepum** [comment]
The issue here is really ghc-mod, not cabal. As far as I understand it, there's nothing about cabal-install that would require an old version to be used for GHC 7.8.4. Since there is a workaround, I'm going to leave this be and focus on GHC 7.10.x.
