### ISSUE TITLE
Serving .hs files as a FastCGI?

### ISSUE THREAD

**Issue by maerten** [ghcformacosx/ghc-dot-app#37]
In a way this tool reminds me of LAMP/WAMP/XAMPP (https://www.apachefriends.org/index.html). These tools are a nice way to start with PHP development, by writing .php files to the webroot and reloading in the browser.

As ghcformacosx is the easiest way to get GHC and cabal running on a Mac, I thought it could be nice for ghcformacosx to also add the option to serve .hs files from a specified webfolder, and have it work similarly like XAMPP, so without need for compilation with ghc / cabal.
So it could have another checkbox: [] serve .hs files from this directory: [ ............. ]

Sure it's not the way to build an actual website with Haskell, but it sure would be enough to get people try out Haskell and maybe some templating libraries. At least then beginners will not have to jump straight the terminal to play a bit with haskell and build some small projects on their own workstation.

**Comment by etrepum** [comment]
That's quite an interesting idea, but unfortunately very much out of scope for this project!
