### ISSUE TITLE
7.8.4 package breaks on OS X El Capitan

### ISSUE THREAD

**Issue by LukeHoersten** [ghcformacosx/ghc-dot-app#39]
See https://github.com/haskell/cabal/issues/2653

Basically cabal-install needs to be built against the latest unix package.

**Comment by etrepum** [comment]
Is there a suitable binary available? It's an easy fix if there is, the build process for ghc-dot-app uses a precompiled binary.

**Comment by LukeHoersten** [comment]
I'll get back to you on that.

I haven't moved to 7.10.1 yet because my applications perform 4x slower in benchmarks.

**Comment by LukeHoersten** [comment]
@etrepum need you to chime in on the latest comments on the linked issue. The nuances of the discussion are beyond what I have experience with. Perhaps you can give some guidance on what exactly is needed to make the 7.8.4 ghcformacosx package work on OS X 10.11.

**Comment by etrepum** [comment]
I just need a binary of cabal-install to ship with it

**Comment by etrepum** [comment]
If it's the cabal package in GHC that's the problem then we need a new GHC build that fixes it.

**Comment by etrepum** [comment]
Sounds like the GHC team decided not to do a release for this. Perhaps you can work with them to try and track down why your benchmarks got worse? Surely they'd be interested in fixing that.

https://ghc.haskell.org/trac/ghc/blog/weekly20150721

**Comment by LukeHoersten** [comment]
Sounds good. The workaround is compiling your own unix package so it's not
show stopping.
