### ISSUE TITLE
Update to 7.10.3

### ISSUE THREAD

**Issue by jhenahan** [ghcformacosx/ghc-dot-app#43]
https://mail.haskell.org/pipermail/ghc-devs/2015-December/010736.html

**Comment by TimothyKlim** [comment]
:+1:

**Comment by etrepum** [comment]
Unfortunately I do not have time for this right now, happy to dish out maintainer rights to anyone who can take over. Otherwise, it might be a while until I find the time to dig in to this.

**Comment by gbaz** [comment]
@etrepum, I'll try to do a build this weekend as the whole thing is sorely problematic on el capitan :-)
