### ISSUE TITLE
cabal from ghc-7.10.3.app installs packages to ~/Library/Haskell/ghc-7.10.2-x86_64/

### ISSUE THREAD

**Issue by alexeymuranov** [ghcformacosx/ghc-dot-app#48]
My cabal from ghc-7.10.3.app installs packages to ~/Library/Haskell/ghc-7.10.2-x86_64/lib.  This does not seem normal.  Is this a bug, or have i misconfigured my installation?

**Comment by alexeymuranov** [comment]
Hm, sorry, i am not sure anymore it does, i'll check what is going on. I'll close this for now.

**Comment by jhenahan** [comment]
If you used a pkg installer previously, it may be that your `.cabal/config` was set to install there. Nuking `~/.cabal` and running `cabal update` should fix it if this happens again in the future.

**Comment by alexeymuranov** [comment]
Thanks for advice.

I think now that my `~/Library/Haskell/ghc-7.10.2-x86_64/` was a leftover from some of my previous installations. For some reason it had a recent modification time, this is why i though that packages were installed there. I think now they are well installed to `~/.cabal`.
